-- 29. Департаменты, не принимавшие сотрудников в 2004-2005 гг. (исключая безменеджерные)
SELECT d.*
FROM HR.DEPARTMENTS d
WHERE d.MANAGER_ID IS NOT NULL
AND d.DEPARTMENT_ID NOT IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM HR.EMPLOYEES
    WHERE EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 2004 AND 2005
);
