-- 40. Список сотрудников, которые являются руководителями департаментов
SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY, e.DEPARTMENT_ID, e.PHONE_NUMBER, e.EMAIL
FROM HR.EMPLOYEES e
WHERE e.EMPLOYEE_ID IN (SELECT d.MANAGER_ID FROM HR.DEPARTMENTS d WHERE d.MANAGER_ID IS NOT NULL);
